---
minikube_version: 0.13.1
minikube_checksum: "sha256:52706da92b6cf9a5eb4f59fe6034f119e3eb442c3fc57bf181d01db929e1289f"
minikube_download_url: http://storage.googleapis.com/minikube/releases/v
docker_api_version: 1.23
